spring.application.name=file-management-api
server.port=8081
jwt.secret=MyVerySecretKeyForJwtAuthenticationDemo123456789
jwt.expiration=3600000
#https://start.spring.io/
#http://localhost:8081/v3/api-docs
#http://localhost:8081/swagger-ui/index.html
#Using generated security password: e3c7208f-edb6-4e9d-86ab-30b40ea5ee9b